export const wordList = [
  {word: 'ice cream', image: new URL('./assets/images/ice-cream.jpg', import.meta.url).href},
  {word: 'donut', image: new URL('./assets/images/donut.jpg', import.meta.url).href},
  {word: 'pizza', image: new URL('./assets/images/pizza.jpg', import.meta.url).href},
  {word: 'hamburger', image: new URL('./assets/images/hamburger.jpg', import.meta.url).href},
  {word: 'apple', image: new URL('./assets/images/apple.jpg', import.meta.url).href},
  {word: 'banana', image: new URL('./assets/images/banana.jpg', import.meta.url).href},
  {word: 'cat', image: new URL('./assets/images/cat.jpg', import.meta.url).href},
  {word: 'dog', image: new URL('./assets/images/dog.jpg', import.meta.url).href},
  {word: 'elephant', image: new URL('./assets/images/elephant.jpg', import.meta.url).href},
  {word: 'fish', image: new URL('./assets/images/fish.jpg', import.meta.url).href},
  {word: 'giraffe', image: new URL('./assets/images/giraffe.jpg', import.meta.url).href},
  {word: 'horse', image: new URL('./assets/images/horse.jpg', import.meta.url).href},
  {word: 'cupcake', image: new URL('./assets/images/cupcake.jpg', import.meta.url).href},
  {word: 'salad', image: new URL('./assets/images/salad.jpg', import.meta.url).href},
  {word: 'steak', image: new URL('./assets/images/steak.jpg', import.meta.url).href},
  {word: 'pasta', image: new URL('./assets/images/pasta.jpg', import.meta.url).href},
  {word: 'cake', image: new URL('./assets/images/cake.jpg', import.meta.url).href},
  {word: 'pancake', image: new URL('./assets/images/pancake.jpg', import.meta.url).href},
  {word: 'sandwich', image: new URL('./assets/images/sandwich.jpg', import.meta.url).href},
  {word: 'ball', image: new URL('./assets/images/ball.png', import.meta.url).href},
  {word: 'watermelon', image: new URL('./assets/images/watermelon.png', import.meta.url).href},
  {word: 'tiger', image: new URL('./assets/images/tiger.jpg', import.meta.url).href},
  {word: 'dragon', image: new URL('./assets/images/dragon.jpg', import.meta.url).href},
  {word: 'waffle', image: new URL('./assets/images/waffle.jpg', import.meta.url).href},
  {word: 'mouse', image: new URL('./assets/images/mouse.jpg', import.meta.url).href},
  {word: 'hat', image: new URL('./assets/images/hat.jpg', import.meta.url).href},
]; 